---
- name: add influx repo
  tags:
    - telegraf
    - configure
    - repo
  copy: src=influxdb.repo dest=/etc/yum.repos.d/influxdb.repo mode=644 owner=root group=root

- name: Create target directory
  tags:
    - telegraf
    - configure
  file: path=/etc/systemd/system/telegraf.service.d state=directory

- name: replace telegraf for custom
  tags:
    - telegraf
    - configure
  copy: src=telegraf dest=/usr/bin/telegraf mode=744 owner=root group=root

- name: install smartctl
  yum: name=smartmontools state=installed
  tags:
    - telegraf
    - install

- name: telegraf permissions root
  tags:
    - telegraf
    - configure
  copy: src=override.conf dest=/etc/systemd/system/telegraf.service.d/override.conf mode=644 owner=root group=root

- name: install telegraf
  yum: name={{ item }} state=installed
  tags:
    - telegraf
    - install
  with_items:
    - telegraf
    - lm_sensors

- name: install ipmitool
  yum: name=ipmitool state=installed
  tags:
    - telegraf
    - install

- name: add ipmi modules
  tags:
    - telegraf
    - configure
  copy: src=rc.modules dest=/etc/rc.modules mode=755 owner=root group=root


- name: config telegraf
  template: src="{{ item.name }}.j2" dest="{{ item.path }}{{ item.name }}" mode={{ item.mode }} owner={{ item.owner }} group={{ item.group }}
  notify:
    - restart telegraf
  tags:
    - telegraf
    - configure
  with_items:
    - { name: 'telegraf.conf', path: '/etc/telegraf/', mode: '0640', owner: 'root', group: 'root' }
    - { name: 'service_list', path: '/etc/telegraf/', mode: '0644', owner: 'root', group: 'root' }
    - { name: 'exec.sh', path: '/etc/telegraf/', mode: '0655', owner: 'root', group: 'root' }
